name: nutri_byte
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  material_color_utilities: ^0.5.0
  syncfusion_flutter_charts: 24.1.45
  flutter_svg: ^2.0.9
  form_validator: ^2.1.1
  gradient_progress_bar: ^1.0.4
  permission_handler: ^11.1.0
  camera: ^0.10.5+8
  flutter_tflite: ^1.0.1
  image: ^3.3.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - images/placeholder.png
    - assets/model/
  fonts:
    - family: Signika
      fonts:
        - asset: fonts/Signika/static/Signika-Bold.ttf
          weight: 700
        - asset: fonts/Signika/static/Signika-Light.ttf
          weight: 300
        - asset: fonts/Signika/static/Signika-Medium.ttf
          weight: 500
        - asset: fonts/Signika/static/Signika-Regular.ttf
        - asset: fonts/Signika/static/Signika-SemiBold.ttf
          weight: 600
  uses-material-design: true
