name: nutri_byte
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  material_color_utilities: ^0.5.0
  syncfusion_flutter_charts: 24.1.45
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Signika
      fonts:
        - asset: fonts/Signika/static/Signika-Bold.ttf
          weight: 700
        - asset: fonts/Signika/static/Signika-Light.ttf
          weight: 300
        - asset: fonts/Signika/static/Signika-Medium.ttf
          weight: 500
        - asset: fonts/Signika/static/Signika-Regular.ttf
        - asset: fonts/Signika/static/Signika-SemiBold.ttf
          weight: 600
  uses-material-design: true
